_target_: src.models.peptide_module.GraphLevelGNN
lr: 0.0001
weight_decay: 0.05
result_path: ${data_dir}/peptide/result.csv

net:
  _target_: src.models.components.gnn.GraphGNNModel
  c_in: 22
  c_out: 1
  c_hidden: 24
  num_layers: 3
  # "GCN": geom_nn.GCNConv, "GAT": geom_nn.GATConv, "GraphConv": geom_nn.GraphConv
  layer_name: "GCN"
  dp_rate: 0.1
  dp_rate_linear: 0.2
