_target_: src.models.peptide_module.GraphLevelGNN
lr: 0.0001
weight_decay: 0.1

# 要求有超参数
result_path: ${data_dir}/peptide/${hydra:job.num}

net:
  _target_: src.models.components.gnn.GraphGNNModel
  c_in: 22
  c_out: 1
  c_hidden: 32
  num_layers: 4
  # "GCN": geom_nn.GCNConv, "GAT": geom_nn.GATConv, "GraphConv": geom_nn.GraphConv
  layer_name: "GAT"
  dp_rate: 0.1
  dp_rate_linear: 0.2

loss:
  _target_: src.models.components.loss.FocalLoss
  gamma: 2
  alpha: 0.25
  reduction: 'mean'
  smooth: 0.9
