# @package _global_

# specify here default evaluation configuration
defaults:
  - _self_
  - datamodule: phla.yaml # choose the datamodule for evaluation
  - model: phla.yaml
  - callbacks: null
  - logger: null
  - trainer: default.yaml
  - log_dir: evaluation.yaml

  - experiment: null

  # enable color logging
  - override hydra/hydra_logging: colorlog
  - override hydra/job_logging: colorlog

original_work_dir: ${hydra:runtime.cwd}

data_dir: ${original_work_dir}/data

print_config: True

ignore_warnings: True

seed: null

name: "phla"

# passing checkpoint path is necessary
ckpt_path: ${original_work_dir}/logs/experiments/runs/phla_transformer/2022-04-14_15-51-37/checkpoints/epoch_007.ckpt
