# @package _global_

# specify here default evaluation configuration
defaults:
  - _self_
  - datamodule: peptide.yaml # choose the datamodule for evaluation
  - model: peptide.yaml
  - callbacks: null
  - logger: null
  - trainer: default.yaml
  - log_dir: evaluation.yaml

  - experiment: null

  # enable color logging
  - override hydra/hydra_logging: colorlog
  - override hydra/job_logging: colorlog

original_work_dir: ${hydra:runtime.cwd}

data_dir: ${original_work_dir}/data

print_config: True

ignore_warnings: True

seed: null

name: "peptide_gnn"

# passing checkpoint path is necessary
ckpt_path: ${original_work_dir}/logs/experiments/multiruns/peptide_gnn/2022-05-20_14-47-00/1/checkpoints/epoch_083.ckpt
