_target_: src.datamodules.pepsmi_datamodule.Peptide_smilesModuleV3

#train_data_path: ${data_dir}/AOMP_B27_05/train_unbalanced.txt
#val_data_path: ${data_dir}/AOMP_B27_05/val_unbalanced.txt
#test_data_path: ${data_dir}/AOMP_B27_05/test_unbalanced.txt
#toy_data: True
vocab_path: ${data_dir}/AOMP/vocab.txt
batch_size: 2048
data_path: ${data_dir}/AOMP_ALL_RAW/20k.txt
