_target_: src.datamodules.phla_gmt_datamodule.PeptideModule

train_data_path: ${data_dir}/AOMP/train_data_fold0.csv
val_data_path: ${data_dir}/AOMP/val_data_fold0.csv
test_data_path: ${data_dir}/AOMP/val_data_fold1.csv
batch_size: 2048
toy_data: True